## Numpy Assignment
Student Name:

## Instructions:
- Please complete the questions below.
- for each cell, complete it with good essays and code examples
- Please comment your code indicating how you approached the problem

My name is Adeke Mary doing a Bachelor of Information Technology at Mbarara University of Science and Technology

# What is NumPy, and what are some of its key features?


In [24]:
# to install numpy when you have python installed.

#conda install numpy or 

#pip install numpy

In [ ]:
#importing numpy(Numerical python-its an open source python library)
import numpy as np

# How do you create a NumPy array using Python's built-in range() function?


In [2]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In Python, the built-in range function is used to generate a sequence of numbers, commonly for looping or iterating through a set of values. However, it does not produce an actual list or array unless explicitly converted.

NumPy’s array function allows you to create an array from a variety of data types, such as lists or ranges, making data manipulation and numerical operations more efficient.

The arange function, also from NumPy, is similar to range but is designed specifically to return NumPy arrays. It allows more flexibility, such as using decimal step values, and is widely used in scientific and mathematical computations.

# What is the difference between a scalar value and a vector in NumPy?
with code example

In [ ]:
# Scalar
scalar = np.array(5) #no dimensions
print("Scalar:", scalar)
print("Scalar shape:", scalar.shape)

# Vector
vector = np.array([1, 2, 3])
print("Vector:", vector)
print("Vector shape:", vector.shape)

Scalar: 5
Scalar shape: ()
Vector: [1 2 3]
Vector shape: (3,)


A scalar is a 0 dimensional array while a vector a one-dimensional array that holds a sequence of values
.shape attribute in NumPy returns the dimensions of an array as a tuple

# How do you calculate the mean of a NumPy array using the mean() function?

Examples 



In [5]:
arr = np.array([10, 20, 30, 40])
value = np.mean(arr)
print(value)

arr = np.array(range(2,20,2))
average = np.mean(arr)
print(average)


25.0
10.0


The mean() function in NumPy is used to compute the average (arithmetic mean) of array elements.

# What is broadcasting in NumPy, and how can it be useful?


In [6]:
data = np.array([1, 2, 3])
b = data + 10

print(b)

[11 12 13]


Broadcasting is a mechanism that allows numpy to perform basic operations on arrays of different shapes. for example if its multiplication, numpy understands that it should happen with each cell.
it simplifies code and improves performance(faster and uses less memory)

# How can you slice a NumPy array to extract a subarray?




In [10]:
data = np.array([10, 20, 30, 40, 50])

subarray = data[1:4] # Extract elements from index 1 to 3 (excluding index 4)
print(subarray)


# Access the third element (index 2)
print(data[2]) 

# Access the last element
print(data[-1])  

# Access the second last element
print(data[-2])  

# Get the last three elements
print (data[-3:]) 

# Reverse the entire array
print(data[::-1])  

[20 30 40]
30
50
40
[30 40 50]
[50 40 30 20 10]


Slicing in NumPy allows you to extract a portion (subarray) of an array by specifying start, stop, and step indices using the colon : syntax

In NumPy, positive indexing allows access to elements starting from the beginning of the array, where index 0 refers to the first element. Negative indexing starts from the end, so index -1 refers to the last element, -2 to the second last, and so on.

You can slice arrays to extract subarrays by specifying a start and stop index. For example, slicing from index 1 to 4 returns the second to fourth elements. You can also include a step value to skip elements, such as getting every second element in the array.

Reversing an array is possible using slicing with a step of -1. In two-dimensional arrays, you can access specific rows by indexing with a single number, and specific columns using slicing along the second axis. Negative indexing also works in two dimensions, allowing access to the last row or column.

# What are some of the available functions for performing element-wise operations on NumPy arrays?


In [ ]:
age = np.arange(1, 51, 2)
print(age)


print(np.add(age, 5)) # Add 5 to each element
print(np.subtract(age, 1))  # Subtract 1 from each element
print(np.multiply(age, 2))  # Multiply each element by 2
print(np.divide(age, 2))    # Divide each element by 2
print(np.power(age, 2))     # Square each element
print(np.mod(age, 2))       # Modulus (remainder) of each element by 2

print(np.mean(age))         # Mean of all elements
print(np.median(age)) 



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52
 54]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[ 2  6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78 82 86 90 94
 98]
[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5 19.5 20.5 21.5 22.5 23.5 24.5]
[   1    9   25   49   81  121  169  225  289  361  441  529  625  729
  841  961 1089 1225 1369 1521 1681 1849 2025 2209 2401]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
25.0
25.0
[0. 1. 2. 2. 3. 4. 4. 5. 6.]
[1. 2. 2. 3. 4. 4. 5. 6. 6.]


# How do you reshape a NumPy array to have a different shape?





In [17]:
weight = np.arange(12)  # 1D array with 12 elements
print(weight)

reshaped_weight = weight.reshape(3, 4)  # Reshape to 3 rows, 4 columns
print(reshaped_weight)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In NumPy, you can reshape an array using the .reshape() function to change its structure without changing the data

# How do you perform matrix multiplication on two NumPy arrays using the dot() function?


To perform matrix multiplication in NumPy, you can use the np.dot() function or the @ operator. These perform the dot product, which is standard matrix multiplication (not element-wise).

syntax
np.dot(A, B)
Where A and B are NumPy arrays (matrices or vectors).

but the condition is that number of columns in the first matrix must equal the number of rows in the second matrix.

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Perform matrix multiplication
result = np.dot(A, B)

print(result)

#Row 1 of A × Column 1 of B: 1*5 + 2*7 = 19
#Row 1 of A × Column 2 of B: 1*6 + 2*8 = 22

[[19 22]
 [43 50]]


# How can you use the where() function to apply a condition to a NumPy array?


In [19]:
data = np.array([5, 15, 25, 35, 45])

# Replace values greater than 20 with 1, others with 0
result = np.where(data > 20, 1, 0)

print(result)

[0 0 1 1 1]


np.where() function is used to apply conditions on arrays and selectively choose values based on those conditions.

syntax
np.where(condition, value_if_true, value_if_false)

condition: A logical condition on the array.
value_if_true: Value to assign where the condition is true.
value_if_false: Value to assign where the condition is false.

# What is the difference between the flatten() and ravel() functions in NumPy?




In [20]:
#flatten
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
b[0] = 99

print(a)  # Original remains unchanged


#ravel
c = a.ravel()
c[0] = 88

print(a)  # Might reflect change if view is returned


[[1 2]
 [3 4]]
[[88  2]
 [ 3  4]]


Both flatten() and ravel() are used to convert a multi-dimensional NumPy array into a 1D array, but they behave slightly differently in terms of memory and performance.
flatten()
Returns a copy of the original array, flattened into 1D.
Modifying the flattened array does not affect the original array.
Slightly slower due to copying.

 ravel()
Returns a view (if possible) of the original array.
Modifying the result may affect the original array (if it's a view).
Faster and more memory-efficient.

# How do you use NumPy's advanced indexing capabilities to select specific elements from an array?


In [ ]:
 #1. Integer Array Indexing
#You can use an array or list of integers to select specific elements by position.

arr = np.array([10, 20, 30, 40, 50])

# Select elements at index 0, 2, and 4
selected = arr[[0, 2, 4]]
print(selected)  

 #2. Boolean Array Indexing
#You can pass a Boolean mask (array of True/False) to select elements that satisfy a condition.

# Select elements greater than 25
mask = arr > 25
print(arr[mask])  # Output: [30 40 50]
#Or in one line:
print(arr[arr > 25])  # Output: [30 40 50]

 #3. 2D Integer Indexing
#You can select specific elements from a 2D array using row and column index arrays.


matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rows = [0, 1, 2]
cols = [2, 1, 0]

# Select (0,2), (1,1), and (2,0)
print(matrix[rows, cols])  # Output: [3 5 7]

Advanced indexing in NumPy allows you to access and manipulate specific elements from an array using lists or arrays of indices, rather than simple slicing.

This gives you fine-grained control over which elements to retrieve, especially in non-contiguous or irregular patterns

# How can you use NumPy's broadcasting rules to perform operations on arrays with different shapes?

In [ ]:

#adding a scalar to an array
a = np.array([1, 2, 3])
b = 10

print(a + b)  

#adding a 1D to 2D array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

# B is broadcasted to match each row of A
print(A + B)


Broadcasting in NumPy allows you to perform arithmetic operations on arrays of different shapes as if they had the same shape, without explicitly copying data.

### Project: Array Statistics Calculator
**Description:**

In this project, you will create a program that allows a user to enter a list of numbers, and then calculates and displays various statistics about those numbers using NumPy.

**Requirements:**

- The program should prompt the user to enter a list of numbers separated by commas.
- The program should use NumPy to convert the input into a 1D NumPy array.
- The program should calculate and display the following statistics:
- The mean of the numbers
- The median of the numbers
- The standard deviation of the numbers
- The maximum and minimum values of the numbers
- The program should use appropriate NumPy functions to calculate the statistics.
- The program should display the statistics with appropriate labels.

### Sample Output
```
Enter a list of numbers separated by commas: 2, 5, 7, 3, 1, 9
Statistics for the input array:
Mean: 4.5
Median: 4.0
Standard Deviation: 2.9154759474226504
Maximum: 9
Minimum: 1
```

In [24]:


# Prompt the user to enter a list of numbers
user_input = input("Enter a list of numbers separated by commas: ")

# Convert the input string to a list of floats
number_list = [float(num.strip()) for num in user_input.split(',')]


"""Splits the string at each comma using .split(','), creating a list of string numbers: ['2', '5', '7', ...]

Strips whitespace using strip() from each number.

Converts each string to a float using float().

The result is a list of numbers like [2.0, 5.0, 7.0, 3.0, 1.0, 9.0] stored in number_list."""

# Convert the list to a NumPy array
arr = np.array(number_list)

# Calculate statistics using NumPy functions
mean_val = np.mean(arr)
median_val = np.median(arr)
std_dev = np.std(arr)
maximum = np.max(arr)
minimum = np.min(arr)

# Display the results
print(f"your array:{user_input}")
print("\nStatistics for the input array:")
print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Standard Deviation: {std_dev}")
print(f"Maximum: {maximum}")
print(f"Minimum: {minimum}")


ValueError: could not convert string to float: ''